### ISSUE TITLE
App request

### ISSUE THREAD

**Issue by dabobo2** [AltSourceio/AltSource#1]
Hey on schnapple.com there is a guy who Released quake 1-3 and Doom 3 emulators for idevices. I would dig those apps Since i dont own a .Mac to compile them

Many thx

**Comment by AltSourceio** [comment]
Hi. I don’t have a Mac either so I can’t compile it myself. If I find a precompiled ipa I will add them thnx

**Comment by AltSourceio** [comment]
https://apps.apple.com/bt/app/doom/id336347946

**Comment by AltSourceio** [comment]
Found doom

**Comment by AltSourceio** [comment]
Ok was digging around to see if I had my old MacBook and I found it. I’ll try to compile them

**Comment by AltSourceio** [comment]
To compile doom 3 I require a ”base” folder from the game. I don’t own doom 3 so  if you do please send me the base folder at contactAltSource@gmail.com

**Comment by AltSourceio** [comment]
And for quake 3 I require the baseq3 folder

**Comment by dabobo2** [comment]
U re so cool! I only have the cd/dvd versions but no optical Disc Drive anymore.

**Comment by dabobo2** [comment]
Those schnapple versions are in there for about a year - no one uses them or talk About because no one Compilation them

**Comment by dabobo2** [comment]
Found it here: https://archive.org/details/QuakeIIIGoldUSAEurope

**Comment by AltSourceio** [comment]
Do you own this game? I don’t endorse piracy if you don’t own the game I won’t download it

**Comment by dabobo2** [comment]
Yes i do, i own q1-3 and Doom 3. quake 3 and Doom 3Seems to be Freeware? Its downloadable via Archive.org and the Source code is Even available

**Comment by AltSourceio** [comment]
Ok gimme a day or 2 and it will be on the source! (I’ll close the issue when I push the update)

**Comment by dabobo2** [comment]
Maybe you can Even compile those Projects without the needed Game files so that Other Users can use iTunes file Sharing to put their Game files to the App

**Comment by dabobo2** [comment]
This is fantastic, Thank you so much

**Comment by AltSourceio** [comment]
Maybe

**Comment by AltSourceio** [comment]
Np

**Comment by dabobo2** [comment]
https://archive.org/details/Id_Software_Doom_3_Windows_2004_Eng That is the Archive.org Doom 3 Link. Seems to be free to

**Comment by AltSourceio** [comment]
Gonna be offline for an hr I’ll get back to you when I’m done

**Comment by AltSourceio** [comment]
Wait team arena or arena? For quake

**Comment by dabobo2** [comment]
Ill guess only Arena will work? But i am Not sure

**Comment by dabobo2** [comment]
Maybe you want TO put More Game emulators on your Altsource. Xash3d-ios ipa can Emulate half Life on idevices.
It works very well

**Comment by AltSourceio** [comment]
I downloaded quake 3 and it was only a .bin I need the baseq3 folder

**Comment by dabobo2** [comment]
Hi, this is just The cd image file Format similar to zip. You Can Open it and extract ist with several Tools like: https://www.izarc.org/ (to get the baseq folder the game Needs to be installed)

**Comment by dabobo2** [comment]
Any news?

**Comment by AltSourceio** [comment]
No I unzipped the zip just a bin file (and its the crack of dawn for me I’m in Australia) I’m gonna close this issue if you find the baseq3 and base folder you can email them to me at contactAltSource@gmail.com

**Comment by dabobo2** [comment]
Hey did u get my Mail?
